on:
    push:
    pull_request:
    schedule:
      - cron: "0 7 * * *"
  
name: Test
jobs:
    Build:
      strategy:
        matrix:
          go-version: [1.22.x, 1.23.x, 1.24.x]
          platform:  [ubuntu-latest, windows-latest, macos-latest, macos-13]
      runs-on: ${{ matrix.platform }}
      steps:
        - name: Fetch Repository
          uses: actions/checkout@v4
        - name: Install Go
          uses: actions/setup-go@v5
          with:
            go-version: '${{ matrix.go-version }}'
        - name: Run Test
          run: go test -race -count=1 ./...
  